# https://wiki.internetcomputer.org/wiki/Node_Provider_Self_Declarations
# document present without hash

[0x52]
name = "0x52"
declaration = "42d3114d4cf04edbb2cfffae40ea05707882f3b7198e5804ef67cff5cebc3ece"
identity = "d26479db1dc5e48da70bb117c251af7b36b17db9e8c5180194be070e82b287a3"
handover = "9f8c7049cea647ce9e0431ece9a5b7593517563f651a850f2bad9c63c167ea8e"
wiki-link = "https://wiki.internetcomputer.org/wiki/0X52"

[100]
name = "100 Count Holdings, LLC"
declaration = "f5daccdb2a577ac86e7fbbe709d4a60c97ed8bc2a4c66717bb1f6b8cd19df13c"
identity = "cc42a3bc6f61d8ee2b28de1a329c8207db61fecea5c80c8d1e9912e219df6fc3"
handover = "48e4c859db33eb48007e00761fc0dd0382fc73d0f195cb42067cace63ac104e0"
wiki-link = "https://wiki.internetcomputer.org/wiki/100_Count_Holdings,_LLC"

[43]
name = "43rd Big Idea Films"
declaration = ""
wiki-link = "https://wiki.internetcomputer.org/wiki/43rd_Big_Idea_Films,_LLC"

[87]
name = "87m Neuron, LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/87m_Neuron,_LLC"
declaration = "86cb37d2e3d30305978a951675ffd66f497f3c14c6434ef179eced7ee73e39f9"
identity = "41ee1cc7c50c7884a11d602b2aa3af2dd414761a72a9b0ec18066cf40336939c"
handover = "cce9ed442f3b5aa428413a0994bf814c40db64ccd3c3aaa0a48f016ae63b5e1d"

[accuset]
name = "ACCUSET SOLUTIONS"
wiki-link = "https://wiki.internetcomputer.org/wiki/ACCUSET_SOLUTIONS"
declaration = "26fd3daf90363f4c9c24b78add3f344d7e4f3e765d70d861b08481a9fdcc69fa"
identity = "2722e9ae94c2b1ad596a5937e9ec90dedc76c7b5909ea3b4a48690788ce45912"

[arceau]
name = "Arceau NP LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/Arceau_NP_LLC"
declaration = "b24ab500e3b7a54ed948fdb2e763a2477c6d9529a5adc107c7bfda77df29b335"
identity = "a84db3c6bee54844407d3bbf0c2311b5beb06e6b37ec457f77d476c5a1b81918"
handover = "b855c7ef7738be197db502fca07201353ce360bf8c5f2d2edfa3763494e13459"

[aitubi]
name = "Aitubi AG"
wiki-link = "https://wiki.internetcomputer.org/wiki/Aitubi_AG"
declaration = "867990ecde96b8362eb137911199aafbbaef61ded0805912b36bfb86df689974"
identity = "89e6063e8abc1b76aa4f13b6d2ea9fc1e0fe950e23093565facf3c4cd82e8d3e"

[aksinia]
name = "Aksinia Stavskaya"
wiki-link = "https://wiki.internetcomputer.org/wiki/Aksinia_Stavskaya"
declaration = "fc1342d687c1aeedd10787379bb98d5023a687fe91c612d09b549951437c0fd3"
identity = "8fcdcd9edb3f09d74fa4f4a23f39f358061da06d3fe3d787129d6661f8f8c19a"

[allusion]
name = "Allusion"
wiki-link = "https://wiki.internetcomputer.org/wiki/ALLUSION_BV"
declaration = "ce7805a31ef5f5830a9d6526762c6206b32e2450e82927d2840b57ae9caf7d28"
identity = "dec7a6a2654df1a7164b3dd2472f0fc1e13fabebbe7a5a85d490ee808426717a"

[anypoint]
name = "ANYPOINT PTY LTD"
declaration = "2423220dcd5bc4744d4db65fdce8004f6010c56825f039dd1e270dc8d2b07d3b"
identity = "1a904b830d90beb42166e2b504ba573bb4a6257cbbaf644f37c7487da8bce407"
wiki-link = "https://wiki.internetcomputer.org/wiki/ANYPOINT_PTY_LTD"

[avrvm]
name = "AVRVM AG"
wiki-link = "https://wiki.internetcomputer.org/wiki/AVRVM_AG"
identity = ""
declaration = ""

[artem]
name = "Artem Horodyskyi"
wiki-link = "https://wiki.internetcomputer.org/wiki/Artem_Horodyskyi"
identity = "3f1ec7bf0e8c3be87c9b2a47317947514bb78d81d859e59ec17e6644a82f440e"
declaration = "7ab6456b747b13dfcf3e95754698ff247f7dd7cc6ee5da1ded4a0c81e49d3f69"
hardware = "c90af353a7540387587398e39080d5c20c711adfb26690a8acf1e2430a9d01f2"

[bianca]
name = "Bianca-Martina Rohner"
wiki-link = "https://wiki.internetcomputer.org/wiki/Bianca-Martina_Rohner"
identity = "2c1fa30253103788b7c6510bb1fc66fd4e11b9e9df163ec936c9a460b377ade2"
declaration = "ca3973712c4d7947b0b835368ca0648696d52ff6e7ed69a7c92766c1da51e0ce"

[bigger]
name = "Bigger Capital"
wiki-link = "https://wiki.internetcomputer.org/wiki/Bigger_Capital"
identity = "46ccf5a7d1619d7c839b1e1b11dffc46bfe2419f67365b47fce6338d1d846860"
declaration = "3d084d13fb536b771e68abd52c7ab2046128095159f4d05df23783331070a939"


[bitmoon]
name = "Bitmoon"
wiki-link = "https://wiki.internetcomputer.org/wiki/Bitmoon"
identity = "0B2764C306DD0D46B67DDE4F35AAE7BCFCA3446E3940884EA384B8F6EE97105D"
declaration = "6217297B57728231E6DACD52E68787539B8A07494854E303DEF508B0B9967800"


[blockchain]
name = "Blockchain Development Labs"
wiki-link = "https://wiki.internetcomputer.org/wiki/Blockchain_Development_Labs_Inc"
identity = ""
declaration = "5B5D9AB6103048E9F2FDBC4473525FD850A325F1D03B192ED1C2E72D0FDC29A3"

[blockfinance]
name = "BlockFinance"
wiki-link = "https://wiki.internetcomputer.org/wiki/BlockFinance_LLC"
identity = "b612315036562eb9a1b07757430e2f0995a76f4fb981f36433b8ac6abce453e4"
declaration = "f60e2dae584ddf2cb101767f393d417eb30c9f4552ca116b634a858f8448c6a1"

[blocktech]
name = "BlockTech Ventures, LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/Blocktech_Ventures_LLC"
identity = "bbd9ed4e8b49068f587014edb3aed85fe376de43d6e30794dbd92795fd073a8b"
declaration = "5336e2b4e59742ae655f896d61453bd41883795d9677926abb4b5de9879abf5e"


[blp22]
name = "BLP22, LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/BLP22,_LLC"
identity = "e76a55e659282447f89272cebe484aa221413b4dced7e5d66142d83e94e7389d"
declaration = "9dbabd5e2e2ce3f8dfa19dc78934899c9b43394fd40e8379eab4f2a34b762573"


[blueant]
name = "Blue Ant LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/Blueant_LLC"
identity = ""
declaration = ""


[bohatyrov]
name = "Bohatyrov Volodymyr"
wiki-link = "https://wiki.internetcomputer.org/wiki/Bohatyrov_Volodymyr"
identity = "6abf8dd9bde2f6127be4da609cfa778bbac09405c9978382d037b09b0f55c1bc"
declaration = "82fa2bfb0f25ff19204eb1b8c5fe1209317042fb0ec9333dbbfc7725a29bd5e3"
invoice = "fe1d2612e5307bb5cb86ca85e587f6d49bf39a850a8358ceda36d3839ceb4272"

[buldakova]
name = "Buldakova Rehina"
wiki-link = "https://wiki.internetcomputer.org/wiki/Buldakova_Rehina"
identity = "bc39f6908c7db90d06eddb9348b60a6e21753904b173e4e42a3e1b27654756cd"
declaration = "79831c77930473be111551c497063269b8b2be63f9372fea825171437e41de12"

[carbon]
name = "Carbon Twelve"
wiki-link = "https://wiki.internetcomputer.org/wiki/CarbonTwelve"
identity = "1541c3df1cfb02b76b74096dc9303e8a45e0efc2cd8f2386e0cf5d9726173779"
declaration = "9272f640d2c243ed42476bc3511b9787bd19d4937229eb3aecaf662dd4e55d9d"


[conic]
name = "Conic Ventures"
wiki-link = "https://wiki.internetcomputer.org/wiki/Conic_Ventures"
identity = "68ec5196be0e038f1a99026ba68bd7bf062286b561da9cfa8a47cfd050c641c0"
declaration = "b01a30985df37336173969e30a533000524ce19f77a3dd3f7ebfa1de1db232e3"


[coplus]
name = "Coplus Limited"
wiki-link = "https://wiki.internetcomputer.org/wiki/Coplus_Limited"
identity = ""
declaration = ""


[def]
name = "Decentralized Entities Foundation"
wiki-link = "https://wiki.internetcomputer.org/wiki/Decentralized_Entities_Foundation"
identity = "db50f9440a1c3d8318687afa17ec20c1b3af211eb52ce37cfab4a45ea2466f7c"
declaration = "38734075a8577fc9e1d1ded846b41050f1f0255d5fefad747a9e5660a1c2b67f"
handover = "fd2d272b40734d4164c956156634dd5b23b0d3a327755bdef668ed77005b7db3"

[denode]
name = "DeNoDe"
wiki-link = "https://wiki.internetcomputer.org/wiki/DENODE"
identity = "c5d9a2a647fbfd3d345a026d43fafe48a03c64006d41d302827eefb3dcee43e0"
declaration = "6e46fd7be576166a1af786d805eac8237561645bd2afee2bbfd194888cc9f68b"
handover = "e973ebd05f3f2c0a73d5a4195bdd97854831e0ef70e55a7cbfb83a501f676b93"

[dfinity]
name = "DFINITY Stiftung"
wiki-link = "https://wiki.internetcomputer.org/wiki/DFINITY_Stiftung"
identity = ""
declaration = ""

[eastman]
name = "Eastman Ventures (Pty) Ltd"
wiki-link = "https://wiki.internetcomputer.org/wiki/Eastman_Ventures_Pty_Ltd"
identity = ""
declaration = ""


[exaion]
name = "Exaion"
wiki-link = "https://wiki.internetcomputer.org/wiki/Exaion"
identity = ""
declaration = ""

[extragone]
name = "Extragone SA"
wiki-link = "https://wiki.internetcomputer.org/wiki/Extragone"
identity = "e8a435b81f6412debe94827b67d1aec40e023efae567d01881b0ea9fec6b3902"
declaration = "3665e7a5033c564d33599b170b486fc01300e1a9d9d4e32578d248530523b4e2"
handover = "e7791686676bb6dc5b211a0255151754c47cd63ade9e42548c33773c3da88fc5"

[fenex]
name = "The Fenex Company LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/User:FenexLLC"
identity = "fe0994cb2abc2b0c12d42f61b56b08314b897ca617f2cb4aa4df424b26edfad9"
declaration = "1ac3f6c3eeae84ee4efc72695e440dd62eda9cd7b6c42800ce090a72d7dfd273"

[ferndale]
name = "Ferndale International"
wiki-link = "https://wiki.internetcomputer.org/wiki/Ferndale_International"
identity = "de4f19b3f21c4a8d8d94f177c6e524e39d63710ecc3179d9d2b23a16eef91266"
declaration = "2b8e85fe14fbbb3e3bcbf181ce6c5de1acee61367a45023b949932b1390066f1"

[fractal]
name = "Fractal Labs AG"
wiki-link = "https://wiki.internetcomputer.org/wiki/Fractal_Labs,_LLC"
identity = "ef8029e828140ce48c5ce8ee53a3c8e71c7925cab0147a4e281800d51b6db557"
declaration = "d203530bc0216adcf022772fc609ed70696c31a00e7e71be1129fa6ff70b3e9b"
handover = "ddf7bb6cf777b7b3e85be0062681fddfb942eded73076450eada545bd8c0f763"

[geeta]
name = "Geeta Kalwani"
wiki-link = "https://wiki.internetcomputer.org/wiki/Geeta_Kalwani"
identity = "06d21b40f5d1739418e661cd489aebcc147b41b7e1fc387e3cf3fd13cb960072"
declaration = "454e41ea6b63fc2fc6c25f5353c3138da6d84ff49d92fd422c1db06706355bec"


[geonodes]
name = "GeoNodes LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/GeoNodes_LLC"
identity = ""
declaration = ""
invoice = ""

[george]
name = "George Bassadone"
wiki-link = "https://wiki.internetcomputer.org/wiki/George_Bassadone"
identity = ""
declaration = ""


[geodd]
name = "Geodd Pvt Ltd"
wiki-link = "https://wiki.internetcomputer.org/wiki/Geodd_Pvt_Ltd"
identity = ""
declaration = ""


[giant]
name = "Giant Leaf, LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/Giant_Leaf,_LLC"
identity = "62b777bf1b43b8279aec8da2865ae630166088f3697ae939c802a6224761c0c7"
declaration = "f58b0610cd7472e14336042eb517bd977d4c4d0b27086ade40a16776e7fd3b95"

[honey]
name = "Honeycomb Capital (Pty) Ltd"
wiki-link = "https://wiki.internetcomputer.org/wiki/HoneyComb_Capital"
identity = ""
declaration = ""

[iancu]
name = "Iancu Aurel"
wiki-link = "https://wiki.internetcomputer.org/wiki/Iancu-Aurel"
identity = "5320f55c840a0951eed84443255ffceb2874da00ce95ebae7cf9c61b7a6b8532"
declaration = "5ed8f7717261c608cf8fc1d59a0c4f4b795f65bb694d09912593eddcb7687609"

[icaria]
name = "Icaria Systems Pty Ltd"
wiki-link = "https://wiki.internetcomputer.org/wiki/Icaria_Systems_Pty_Ltd"
identity = "3e5e8e0934d4fd9c386586f2f50936bdb85b10ee778ffe041f028ccf8541d8e1"
declaration = "3c2bec3aeda3318d86ecfa0b646db10f37503914d9946f4551fd845e3b79cbd5"

[illusion]
name = "Illusions In Art (Pty) Ltd"
wiki-link = "https://wiki.internetcomputer.org/wiki/Illusions_in_Art_Ltd"
identity = "27e98c3737462db4f8da258c10eeb10d0fc42a3095f3fa280785b165bcaba993"
declaration = "35e13e1e731a95714108d44be84cb2ea6b2a42299c1100f40e779704f4ee3d3b"

[info]
name = "InfoObjects"
wiki-link = "https://wiki.internetcomputer.org/wiki/InfoObjects_Inc"
identity = ""
declaration = ""

[ivanov]
name = "Ivanov Oleksandr"
wiki-link = "https://wiki.internetcomputer.org/wiki/Ivanov_Oleksandr"
identity = "723aa68d984f37822e7da2e1e137d1c465288d49f96aa09f971954c076d0026f"
declaration = "577537d188a10394b290bdcbf68973aee61f7304e59181441e5dfc5a5dbd63bb"
invoice = "cfa52fc312116003e3e48c634a6267a9ec4c3a3afbb6aa29d4db1e4989097780"

[karel]
name = "Karel Frank"
wiki-link = "https://wiki.internetcomputer.org/wiki/Karel_Frank"
identity = ""
declaration = ""


[katerina]
name = "Katerina Karapuz"
wiki-link = "https://wiki.internetcomputer.org/wiki/Katerina_Karapuz"
identity = "965e28cfb17df505534fe72dcb29cdd43fe1eb74b5e9106d168f466fdea072dd"
declaration = "e4a1b47b5a5544282b87d50027ee68138d790ba3f6b04ed98736f24a40871ab0"


[kontrapunt]
name = "Kontrapunt (Pty) Ltd"
wiki-link = "https://wiki.internetcomputer.org/wiki/Kontrapunt_(Pty)_Ltd"
identity = "2b816da720ac366647a68350d03a0742e5a361160de2c9768464a0ff18a883a5"
declaration = "4a3dcb2d4be1dad6f1cc8b6c124083284ade988618a73ae196514d763805d218"


[krishna]
name = "Krishna Enterprises"
wiki-link = "https://wiki.internetcomputer.org/wiki/Krishna_Enterprises"
# split
identity = ""
declaration = ""
invoice = ""

[krzysztof]
name = "Krzysztof Å»elazko"
wiki-link = "https://wiki.internetcomputer.org/wiki/Krzysztof_%C5%BBelazko"
identity = "0a5cfdd7efa057413bdc74b7e3Cb707c46f6c84fd5f0e6a4d9f9bd7eccd5712d"
declaration = "ac47b0a59d4509975e09209e4c218a418c01ade4187b6b7e6bea1b2ac153fa62"

[louise]
name = "Louise Velayo"
wiki-link = "https://wiki.internetcomputer.org/wiki/Louise_Velayo"
identity = "20b9d99195d7a157833fc399d6c94c05b6ba80fc43095f88002eab9b023dcebc"
declaration = "2b425dbb1a6a4030157f0b0f9a6d2950f67b1fe72fb68ed088a6f3e4cd735694"


[lukas]
name = "Lukas Helebrandt"
wiki-link = "https://wiki.internetcomputer.org/wiki/Lukas_Helebrandt"
identity = ""
declaration = ""

[marvelous]
name = "Marvelous Web3"
wiki-link = "https://wiki.internetcomputer.org/wiki/Marvelous_Web3"
identity = ""
declaration = ""

[maksym]
name = "Maksym Ishchenko"
wiki-link = "https://wiki.internetcomputer.org/wiki/Maksym_Ishchenko"
identity = "d1f00e96f1042037235767210b105f72f4cbaa94aa34be84a0400bacb2ca4e77"
declaration = "e93de8d5b1ebe292df3bdbb781537bae0b478ab9d1242b65a8ac1f92cb1e95d7"
invoice = "3ee9fa7343991112c4f43fc808ec6bcdd9c320dfc9d8d07a1675934863c62f97"

[ml]
name = "ML SOLUTIONS LTD"
wiki-link = "https://wiki.internetcomputer.org/wiki/File:NODE-PROVIDER-SELF.pdf"
identity = ""
declaration = "f92612f76063cfd7270a2010a184085d83a1cb43d45d6eec649ae928fb9a4d6e"

[mi]
name = "MI Servers"
wiki-link = "https://wiki.internetcomputer.org/wiki/MI_Servers"
identity = "5520f569efcf2f8d17df86b719438d5e7c5674ba6f4267b37d0bfe6150a179c7"
declaration = "9fc5eac74b983ea375d2c0a10985ecb1b504b53df5ac6615f726a71625a63daa"
handover = "48e4c859db33eb48007e00761fc0dd0382fc73d0f195cb42067cace63ac104e0"

[mariano]
name = "Mariano Stoll"
wiki-link = "https://wiki.internetcomputer.org/wiki/Mariano_Stoll"
identity = "292d36140c03081b63bd76ec7758ce2654c9e7b4ee5d086b14915f09554d2ef6"
declaration = "549b11c43bd4d4705066ee24a65ce530d67f9db35d9f4b406700d866c3d4d85a"

[neptune]
name = "Neptune Partners"
wiki-link = "https://wiki.internetcomputer.org/wiki/Neptune_Partners"
identity = "78588307b8273d3b9ac7f4e26194c76da7a5c74aea91b4246def566ab97cd568"
declaration = "212c43503bbbe421e213a7b46da2c91c70c80ae7326b91d2ddedc29f4e26a984"
invoice = "35712cda62bf07210b3851365dfec40d356265caa549e2b69b899e96f6849102"

[nodal]
name = "NODAL CAPITAL"
wiki-link = "https://wiki.internetcomputer.org/wiki/NODAL_CAPITAL"
identity = "9c0ff8a4bd195b0dc76b0c4bdd4e46d33b7e7484b07696bdbfe5f57594c8c6ad"
declaration = "0af318f022d942aacd55b2bca683437b8787bee7fbd88dee0eefefde073d3bef"

[nodao]
name = ""
wiki-link = "https://wiki.internetcomputer.org/wiki/NODAO"
identity = "ba4fd2ee3fe5856a8ed62fb30dd03ecb50e18d22bd040dc5b26dc2da1f11b318"
declaration = "110bea1dfcaf3c8d1a5a7c7c6b453e60c95c70268d4093b74b0321e857bc316c"
handover = "166f1537e12fc673591c55b3c26985f20060ab2d618864fff709a619554c8865"
handover_02 = "a24bcba0528bf63937b9de36a52c5c222a8c65d12774ac23973adbdd5df307ed"

[novi]
name = "NoviSystems, LLC"
wiki-link = "https://wiki.internetcomputer.org/wiki/NoviSystems"
identity = ""
declaration = "c3d8ef713908aa1cc170fb07ff402c424ea7b44658a1c9845062c83d2a142506"


[""]
name = ""
wiki-link = ""
identity = ""
declaration = ""
